export const mockOffers = {
  Exceptions: {
    Errors: [],
  },
  Offers: [
    {
      IsRecomended: true,
      MerchantId: 5476389,
      Name: "CBAZAAR-World's Largest Online Indian Ethnic Wear",
      Description: "CBAZAAR-World's Largest Online Indian Ethnic Wear",
      Img: [
        {
          Kind: "LOGORECT",
          Ordinal: 20,
          URL: "https://storage.googleapis.com/wl-image/e02f6305ab0a21ecc1813dceec2c1066bc1a3b64",
          Width: 210,
          Height: 250,
        },
        {
          Kind: "LOGO",
          Ordinal: 1,
          URL: "https://storage.googleapis.com/wl-image/b457fd56e811e92e6a54a6a98eacb96910edb3c6",
          Width: 200,
          Height: 200,
        },
      ],
      Category: "Women",
      categoryType: "shopping",
      OfferType: "Online only",
      Score: 0,
      URL: "http://www.cbazaar.com",
    },
    {
      IsRecomended: true,
      MerchantId: 5476389,
      Name: "Clarks",
      Description: "Clarks",
      Img: [
        {
          Kind: "LOGORECT",
          Ordinal: 20,
          URL: "https://www.clarks.in/_nuxt/img/logo.4463386.png",
          Width: 210,
          Height: 250,
        },
        {
          Kind: "LOGO",
          Ordinal: 1,
          URL: "https://www.clarks.in/_nuxt/img/logo.4463386.png",
          Width: 200,
          Height: 200,
        },
      ],
      Category: "Appeals",
      categoryType: "shopping",
      OfferType: "Online only",
      Score: 0,
      URL: "https://www.clarks.in/",
    },
    {
      IsRecomended: true,
      MerchantId: 5476389,
      Name: "CashApp",
      Description: "CashApp",
      Img: [
        {
          Kind: "LOGORECT",
          Ordinal: 20,
          URL: "https://www.logo.wine/a/logo/Cash_App/Cash_App-Logo.wine.svg",
          Width: 210,
          Height: 250,
        },
        {
          Kind: "LOGO",
          Ordinal: 1,
          URL: "https://www.logo.wine/a/logo/Cash_App/Cash_App-Logo.wine.svg",
          Width: 200,
          Height: 200,
        },
      ],
      Category: "Finance",
      categoryType: "other",
      OfferType: "Online only",
      Score: 0,
      URL: "https://cash.app/",
    },
    {
      IsRecomended: true,
      MerchantId: 5476389,
      Name: "Nintendo",
      Description: "Nintendo",
      Img: [
        {
          Kind: "LOGORECT",
          Ordinal: 20,
          URL: "https://www.logo.wine/a/logo/Nintendo/Nintendo-Logo.wine.svg",
          Width: 210,
          Height: 250,
        },
        {
          Kind: "LOGO",
          Ordinal: 1,
          URL: "https://www.logo.wine/a/logo/Nintendo/Nintendo-Logo.wine.svg",
          Width: 200,
          Height: 200,
        },
      ],
      Category: "Toys & Games",
      categoryType: "other",
      OfferType: "Online only",
      Score: 0,
      URL: "https://www.nintendo.com/us/",
    },
    {
      IsRecomended: true,
      MerchantId: 5476389,
      Name: "Sony",
      Description: "Sony",
      Img: [
        {
          Kind: "LOGORECT",
          Ordinal: 20,
          URL: "https://sony.scene7.com/is/image/sonyglobalsolutions/529_category?$goldenAreaImage$&fmt=png-alpha",
          Width: 210,
          Height: 250,
        },
        {
          Kind: "LOGO",
          Ordinal: 1,
          URL: "https://sony.scene7.com/is/image/sonyglobalsolutions/529_category?$goldenAreaImage$&fmt=png-alpha",
          Width: 200,
          Height: 200,
        },
      ],
      Category: "Electronics",
      categoryType: "other",
      OfferType: "Online only",
      Score: 0,
      URL: "https://www.sony.co.in/interchangeable-lens-cameras",
    },
    {
      IsRecomended: true,
      MerchantId: 5476389,
      Name: "Nike",
      Description: "Nike",
      Img: [
        {
          Kind: "LOGORECT",
          Ordinal: 20,
          URL: "https://i.pinimg.com/736x/20/60/2d/20602d43cc993811e5a6bd1886af4f33.jpg",
          Width: 210,
          Height: 250,
        },
        {
          Kind: "LOGO",
          Ordinal: 1,
          URL: "https://i.pinimg.com/736x/20/60/2d/20602d43cc993811e5a6bd1886af4f33.jpg",
          Width: 200,
          Height: 200,
        },
      ],
      Category: "Shoes",
      categoryType: "shopping",
      OfferType: "Online only",
      Score: 0,
      URL: "https://www.nike.com/in",
    },
    {
      IsRecomended: true,
      MerchantId: 5476389,
      Name: "Puma",
      Description: "Puma",
      Img: [
        {
          Kind: "LOGORECT",
          Ordinal: 20,
          URL: "https://i.pinimg.com/736x/66/f1/ed/66f1edd300d1f37b10f6922261313014.jpg",
          Width: 210,
          Height: 250,
        },
        {
          Kind: "LOGO",
          Ordinal: 1,
          URL: "https://i.pinimg.com/736x/66/f1/ed/66f1edd300d1f37b10f6922261313014.jpg",
          Width: 200,
          Height: 200,
        },
      ],
      Category: "Shoes",
      categoryType: "shopping",
      OfferType: "Online only",
      Score: 0,
      URL: "https://in.puma.com/in",
    },
    {
      ID: 5507347,
      Name: "eBid",
      Description: "eBid",
      Img: [
        {
          ID: 18029,
          Kind: "LOGO",
          Ordinal: 1,
          ImageID: 18029,
          URL: "https://storage.googleapis.com/wl-image/7a75bb13ee8d78c95e641abd98341fabebaffdfa",
          Width: 200,
          Height: 200,
        },
        {
          ID: 18030,
          Kind: "LOGORECT",
          Ordinal: 1,
          ImageID: 18030,
          URL: "https://storage.googleapis.com/wl-image/49dd40cfd9da3d9f33c22e175313ab8826989628",
          Width: 260,
          Height: 200,
        },
      ],
      Score: 0,
      PrimaryCategoryID: 33,
      URL: "http://www.ebid.net/us/register",
      IsRecomended: false,
      Category: "Department Stores",
      categoryType: "groceries",
      OfferType: "Online only",
    },
    {
      ID: 112838,
      Name: "Onetify",
      Description: "Onetify",
      Img: [
        {
          ID: 18481,
          Kind: "LOGO",
          Ordinal: 1,
          ImageID: 18481,
          URL: "https://storage.googleapis.com/wl-image/9c38c67a6205386b4e4826d28166a3ef53515b09",
          Width: 200,
          Height: 200,
        },
        {
          ID: 18482,
          Kind: "LOGORECT",
          Ordinal: 1,
          ImageID: 18482,
          URL: "https://storage.googleapis.com/wl-image/dfa8a7d1e0f80dd7ecc22407df826b5c7c6a2f06",
          Width: 260,
          Height: 200,
        },
      ],
      Score: 0,
      PrimaryCategoryID: 33,
      URL: "https://onetify.com",
      IsRecomended: false,
      Category: "Department Stores",
      categoryType: "groceries",
      OfferType: "Online only",
    },
    {
      ID: 134898,
      Name: "Japanese Taste",
      Description: "Japanese Taste",
      Img: [
        {
          ID: 18776,
          Kind: "LOGO",
          Ordinal: 1,
          ImageID: 18776,
          URL: "https://storage.googleapis.com/wl-image/b406829d91557b858c58027efbefb3a9809967b3",
          Width: 200,
          Height: 200,
        },
        {
          ID: 18777,
          Kind: "LOGORECT",
          Ordinal: 1,
          ImageID: 18777,
          URL: "https://storage.googleapis.com/wl-image/e541c14372bf94f88b15db55e4350fd8efc21929",
          Width: 260,
          Height: 200,
        },
      ],
      Score: 0,
      PrimaryCategoryID: 18,
      URL: "https://japanesetaste.com/",
      IsRecomended: false,
      Category: "Food & Gourmet",
      categoryType: "food-drink",
      OfferType: "Online only",
    },
    {
      ID: 5476249,
      Name: "Cafe Britt Gourmet Coffee",
      Description: "Cafe Britt Gourmet Coffee",
      Img: [
        {
          ID: 9005,
          Kind: "LOGO",
          Ordinal: 10,
          ImageID: 9005,
          URL: "https://storage.googleapis.com/wl-image/72582d5ae751bab7a38a0ba35b98a01a9633d3e6",
          Width: 200,
          Height: 200,
        },
        {
          ID: 9132,
          Kind: "LOGORECT",
          Ordinal: 20,
          ImageID: 9132,
          URL: "https://storage.googleapis.com/wl-image/8a6b9ce936075f180e9a3702856b3e97cb4fb28c",
          Width: 260,
          Height: 200,
        },
      ],
      Score: 0,
      PrimaryCategoryID: 18,
      URL: "http://www.cafebritt.com",
      IsRecomended: false,
      Category: "Food & Gourmet",
      categoryType: "food-drink",
      OfferType: "Online only",
    },
    {
      ID: 77129,
      Name: "Economy Bookings",
      Description: "Economy Bookings",
      Img: [
        {
          ID: 12932,
          Kind: "LOGO",
          Ordinal: 1,
          ImageID: 12932,
          URL: "https://storage.googleapis.com/wl-image/4707882b6fc99956e8e8ac301013f3f64ee6880b",
          Width: 200,
          Height: 200,
        },
        {
          ID: 12933,
          Kind: "LOGORECT",
          Ordinal: 1,
          ImageID: 12933,
          URL: "https://storage.googleapis.com/wl-image/4bf8ba19afa10fa73d7aec6dcbe5a71fbcc1f221",
          Width: 260,
          Height: 200,
        },
      ],
      Score: 0,
      PrimaryCategoryID: 252,
      URL: "https://www.economybookings.com/",
      IsRecomended: false,
      Category: "Car Rental",
      categoryType: "gas-auto",
      OfferType: "Online only",
    },
    {
      ID: 159232,
      Name: "Elife",
      Description: "Elife",
      Img: [
        {
          ID: 18227,
          Kind: "LOGO",
          Ordinal: 1,
          ImageID: 18227,
          URL: "https://storage.googleapis.com/wl-image/8f4e95e082803db6499906c34abf93cf50e4345f",
          Width: 200,
          Height: 200,
        },
        {
          ID: 18228,
          Kind: "LOGORECT",
          Ordinal: 1,
          ImageID: 18228,
          URL: "https://storage.googleapis.com/wl-image/c653a17ae71cede40057dac94890bad1dd49cb97",
          Width: 260,
          Height: 200,
        },
      ],
      Score: 0,
      PrimaryCategoryID: 252,
      URL: "https://elifelimo.com/",
      IsRecomended: false,
      Category: "Car Rental",
      categoryType: "gas-auto",
      OfferType: "Online only",
    },
    {
      ID: 150569,
      Name: "byFood",
      Description: "byFood",
      Img: [
        {
          ID: 8772,
          Kind: "LOGO",
          Ordinal: 1,
          ImageID: 8772,
          URL: "https://storage.googleapis.com/wl-image/2ae6dd3a9793d25b17e4441693821e82ac6e1dd7",
          Width: 200,
          Height: 200,
        },
        {
          ID: 8773,
          Kind: "LOGORECT",
          Ordinal: 1,
          ImageID: 8773,
          URL: "https://storage.googleapis.com/wl-image/eae8c9019269bafd8dd551a85f2e657837e4acc6",
          Width: 260,
          Height: 200,
        },
      ],
      Score: 0,
      PrimaryCategoryID: 251,
      URL: "https://www.byfood.com",
      IsRecomended: false,
      Category: "Vacation Packages",
      categoryType: "travel",
      OfferType: "Online only",
    },
    {
      ID: 37417,
      Name: "aRes Travel",
      Description: "aRes Travel",

      Img: [
        {
          ID: 9633,
          Kind: "LOGO",
          Ordinal: 10,
          ImageID: 9633,
          URL: "https://storage.googleapis.com/wl-image/7b68d5ca14a905bb3887c124e46acf1cf5fa5def",
          Width: 200,
          Height: 200,
        },
        {
          ID: 9821,
          Kind: "LOGORECT",
          Ordinal: 20,
          ImageID: 9821,
          URL: "https://storage.googleapis.com/wl-image/40aed48f61f761f2f3601ef155a48503b89d39d9",
          Width: 260,
          Height: 200,
        },
      ],
      Score: 0,
      PrimaryCategoryID: 251,
      URL: "https://reservations.arestravel.com/site/welcome/14966/discount-attractions-tickets-hotels-packages",
      IsRecomended: false,
      Category: "Vacation Packages",
      categoryType: "travel",
      OfferType: "Online only",
    },
    {
      ID: 5475805,
      Name: "Best Vet Care",
      Description: "Best Vet Care",
      Img: [
        {
          ID: 16963,
          Kind: "LOGO",
          Ordinal: 1,
          ImageID: 16963,
          URL: "https://storage.googleapis.com/wl-image/47df52d58eab1c19dffceac4583f4a147cc6575d",
          Width: 200,
          Height: 200,
        },
        {
          ID: 3220,
          Kind: "LOGORECT",
          Ordinal: 20,
          ImageID: 3220,
          URL: "https://storage.googleapis.com/wl-image/84fa9bbde951325705026dbacef050f9257c0dc9",
          Width: 260,
          Height: 200,
        },
      ],
      Score: 0,
      PrimaryCategoryID: 6,
      URL: "https://www.bestvetcare.com/",
      IsRecomended: false,
      Category: "Animals & Pet Supplies",
      categoryType: "Home-pet",
      OfferType: "Online only",
    },

    {
      ID: 5476164,
      Name: "Budget Pet Care",
      Description: "Budget Pet Care",
      Img: [
        {
          ID: 464,
          Kind: "LOGO",
          Ordinal: 10,
          ImageID: 464,
          URL: "https://storage.googleapis.com/wl-image/5803bffd4a163dd908ce64c20228b7508bce2ee3",
          Width: 200,
          Height: 200,
        },
        {
          ID: 3228,
          Kind: "LOGORECT",
          Ordinal: 20,
          ImageID: 3228,
          URL: "https://storage.googleapis.com/wl-image/6354f83f22d08cb023eea808ae7e6d0d64ee6a55",
          Width: 260,
          Height: 200,
        },
      ],
      Score: 0,
      PrimaryCategoryID: 6,
      URL: "https://www.budgetpetcare.com/",
      IsRecomended: false,
      Category: "Animals & Pet Supplies",
      categoryType: "Home-pet",
      OfferType: "Online only",
    },
    {
      ID: 5482750,
      Name: "SuperBoletería",
      Description: "SuperBoletería",
      Img: [
        {
          ID: 17797,
          Kind: "LOGO",
          Ordinal: 1,
          ImageID: 17797,
          URL: "https://storage.googleapis.com/wl-image/e914aaae1e2300e1342b158f2a48cc6f6856ae33",
          Width: 200,
          Height: 200,
        },
        {
          ID: 17798,
          Kind: "LOGORECT",
          Ordinal: 1,
          ImageID: 17798,
          URL: "https://storage.googleapis.com/wl-image/2d1751f55e0fe4e845b8bd44eb8c09ef68c45aa9",
          Width: 260,
          Height: 200,
        },
      ],
      Score: 0,
      PrimaryCategoryID: 11,
      URL: "https://www.superboleteria.com/page/international-affiliate-programs",
      IsRecomended: false,
      Category: "Arts & Entertainment",
      categoryType: "Dining-enertainment",
      OfferType: "Online only",
    },
    {
      ID: 98714,
      Name: "HideMy.name",
      Description: "HideMy.name",

      Img: [
        {
          ID: 18221,
          Kind: "LOGO",
          Ordinal: 1,
          ImageID: 18221,
          URL: "https://storage.googleapis.com/wl-image/131a8a22362c781ba6ac8f4a02dfe15cf613d6db",
          Width: 200,
          Height: 200,
        },
        {
          ID: 18222,
          Kind: "LOGORECT",
          Ordinal: 1,
          ImageID: 18222,
          URL: "https://storage.googleapis.com/wl-image/64af7963c0c759481eaffcbaa3bb84162fa99b8b",
          Width: 260,
          Height: 200,
        },
      ],
      Score: 0,
      PrimaryCategoryID: 207,
      URL: "https://hide.mn",
      IsRecomended: false,
      Category: "Internet Services",
      categoryType: "Dining-enertainment",
      OfferType: "Online only",
    },
    {
      ID: 5477399,
      Name: "ELEMIS",
      Description: "ELEMIS",
      Img: [
        {
          ID: 5212,
          Kind: "LOGO",
          Ordinal: 1,
          ImageID: 5212,
          URL: "https://storage.googleapis.com/wl-image/c843f647918c8bf1af405e04d7d995aa674c55aa",
          Width: 200,
          Height: 200,
        },
        {
          ID: 11158,
          Kind: "LOGORECT",
          Ordinal: 1,
          ImageID: 11158,
          URL: "https://storage.googleapis.com/wl-image/012b51e4f8ab8b6479903b236abfc2e843315c0a",
          Width: 260,
          Height: 200,
        },
      ],
      Score: 0.01,
      PrimaryCategoryID: 181,
      URL: "https://us.elemis.com",
      IsRecomended: false,
      Category: "Personal Care",
      categoryType: "Health-beauty",
      OfferType: "Online only",
    },
    {
      ID: 83180,
      Name: "In Common",
      Description: "In Common",
      Img: [
        {
          ID: 9070,
          Kind: "LOGO",
          Ordinal: 10,
          ImageID: 9070,
          URL: "https://storage.googleapis.com/wl-image/d42bfff5a49b21f4f43f8106a7938a000620ae35",
          Width: 200,
          Height: 200,
        },
        {
          ID: 9208,
          Kind: "LOGORECT",
          Ordinal: 20,
          ImageID: 9208,
          URL: "https://storage.googleapis.com/wl-image/8c065c0d7f2fa0ac68c8d9bce62ac971808c872f",
          Width: 260,
          Height: 200,
        },
      ],
      Score: 0,
      PrimaryCategoryID: 181,
      URL: "https://www.incommonbeauty.com/",
      IsRecomended: false,
      Category: "Personal Care",
      categoryType: "Health-beauty",
      OfferType: "Online only",
    },
  ],
};

export const noCashbackData = {
  pending: [],
  earned: [],
  transferred: [],
  cashback: null,
};
export const cashbackData = {
  pending: [
    {
      id: 1,
      merchantID: 5483208,
      saleAmount: {
        amount: "195",
        currency: "USD",
      },
      amounts: [
        {
          amount: "0.975",
          currency: "USD",
          splitPart: "DEVICE",
        },
      ],
      status: "PENDING",
      eventDate: "2022-09-27T23:37:28Z",
      logo: "https://cdn.fynd.com/v2/falling-surf-7c8bb8/fyprod/wrkr/company/5842/applications/6523fa5f41f4eb4c10a1d869/application/pictures/free-logo/original/b0ftwtPw4-Sephora-India.webp",
      name: "Sephora",
    },
    {
      id: 2,
      merchantID: 5483208,
      saleAmount: {
        amount: "130",
        currency: "USD",
      },
      amounts: [
        {
          amount: "0.675",
          currency: "USD",
          splitPart: "DEVICE",
        },
      ],
      status: "PENDING",
      eventDate: "2023-09-27T23:37:28Z",
      logo: "https://dhgf5mcbrms62.cloudfront.net/99441508/header-fcHJMd/sAAb9zT-200x200.png",
      name: "novuas",
    },
    {
      id: 3,
      merchantID: 5483208,
      saleAmount: {
        amount: "270",
        currency: "USD",
      },
      amounts: [
        {
          amount: "5.48",
          currency: "USD",
          splitPart: "DEVICE",
        },
      ],
      status: "PENDING",
      eventDate: "2023-09-27T23:37:28Z",
      logo: "https://bathandbodyworks.in/on/demandware.static/Sites-BathAndBodyWorks-Site/-/default/dw6d789e13/images/Logo-B.png",
      name: "bathandbodyworks",
    },
  ],
  earned: [],
  transferred: [],
  cashback: {
    amount: 0,
    currency: "USD",
  },
};
